export function generateFileHeader(): string {
  return [
    '// Auto-generated by @mustafaaksoy41/sharepoint-kit CLI',
    '// Do not edit manually. Run: npx sp-generate-types --config sharepoint.config.ts',
    '',
  ].join('\n');
}

export function generateInterface(
  name: string,
  fields: Array<{ name: string; tsType: string; required: boolean; description?: string }>,
): string {
  const lines: string[] = [];
  lines.push(`export interface ${name} {`);

  for (const field of fields) {
    if (field.description) {
      lines.push(`  /** ${field.description} */`);
    }
    const optional = field.required ? '' : '?';
    lines.push(`  ${field.name}${optional}: ${field.tsType};`);
  }

  lines.push('}');
  return lines.join('\n');
}

export function mapSharePointTypeToTs(spType: string): string {
  switch (spType) {
    case 'Text':
    case 'Note':
    case 'Choice':
      return 'string';
    case 'MultiChoice':
      return 'string[]';
    case 'Number':
    case 'Currency':
      return 'number';
    case 'Boolean':
      return 'boolean';
    case 'DateTime':
      return 'string';
    case 'Lookup':
      return '{ id: number; value: string }';
    case 'User':
      return '{ id: number; email: string; displayName: string }';
    case 'URL':
      return '{ url: string; description: string }';
    case 'Taxonomy':
      return '{ termGuid: string; label: string }';
    case 'Calculated':
      return 'string | number';
    default:
      return 'unknown';
  }
}

export function sanitizeInterfaceName(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9_]/g, '')
    .replace(/^(\d)/, '_$1');
}
